CREATE TABLE IF NOT EXISTS ME_Login(
    IdCliente INT PRIMARY KEY,
    Senha VARCHAR(1024) NOT NULL
);

CREATE TABLE IF NOT EXISTS ME_Clientes(
    IdCliente INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    Nome VARCHAR(256) NOT NULL,
    Email VARCHAR(64) UNIQUE NOT NULL,
    Cidade VARCHAR(64) NOT NULL,
    Rua VARCHAR(64) NOT NULL,
    Bairro VARCHAR(64) NOT NULL,
    Numero INT NOT NULL,
);