CREATE TABLE IF NOT EXISTS ME_Usuario(
    IdUsuario INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Tipo TINYINT NOT NULL,
    CPF VARCHAR(11) UNIQUE NOT NULL,
    Nome VARCHAR(256) NOT NULL,
    Email VARCHAR(64) UNIQUE NOT NULL,
    Cidade VARCHAR(64) NOT NULL,
    Estado CHAR(2) NOT NULL,
    Rua VARCHAR(64) NOT NULL,
    Bairro VARCHAR(64) NOT NULL,
    Numero INT NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    Telefone CHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS ME_Login(
    IdUsuario INT PRIMARY KEY,
    Senha VARCHAR(1024) NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES ME_Usuario(IdUsuario)
);

CREATE TABLE IF NOT EXISTS ME_Orcamento (
    IdOrcamento INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Valor DECIMAL(10,2) NOT NULL,
    DthCriacao BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ME_Categorias (
    IdCategoria INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DescCategoria VARCHAR(128) NOT NULL
)

CREATE TABLE IF NOT EXISTS ME_Solicitacao (
    IdSolicitacao INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Status TINYINT NOT NULL ,
    DescDefeito VARCHAR(512) NOT NULL,
    DescEquipamento VARCHAR(256) NOT NULL,
    DthCriacao BIGINT NOT NULL,
    DthArrumado BIGINT,
    IdOrcamento INT,
    IdUsuario INT NOT NULL,
    IdCategoria INT NOT NULL,
    FOREIGN KEY (IdUsuario) REFERENCES ME_Usuario(IdUsuario),
    FOREIGN KEY (IdCategoria) REFERENCES ME_Categorias(IdCategoria),
    FOREIGN KEY (IdOrcamento) REFERENCES ME_Orcamento(IdOrcamento)
);