export enum EstadosSolicitacao {
  NOVA = 'NOVA',
  REDIRECIONADA = 'REDIRECIONADA',
  ORCADA = 'ORCADA',
  REJEITADA = 'REJEITADA',
  APROVADA = 'APROVADA',
  ARRUMADA = 'ARRUMADA',
  FINALIZADA = 'FINALIZADA'
}
